### ISSUE TITLE
hapiest doesn't want to start

### ISSUE THREAD

**Issue by KenHaffner** [hitranonline/hapiest#43]
I wanted to start happiest on my PC Windows 10, before I did download the last version of Anaconda3. When I try to start happiest by double clicking the happiest.bat I open a command prompt window which asks for the api key which I gave. The batch file will be closed and I tried to restart by using the batch file I get an error ---------------------------
hapiest.exe - Bad Image
---------------------------
C:\Work_Tantronic\hapi\bin\python36.dll is either not designed to run on Windows or it contains an error. Try installing the program again using the original installation media or contact your system administrator or the software vendor for support. Error status 0xc000007b. 
---------------------------
OK   
---------------------------
May I ask you to help me, thank you in advance.
Best Ken

**Comment by KenHaffner** [comment]
I solved the issue, I have just reboot the PC after installation!

**Comment by jkarns275** [comment]
Glad you managed to resolve the issue! If you encounter any other difficulties dont hesitate to open another issue. 
That said, I'm not really sure what may have caused your original issue, so I'll leave this open just in case others encounter the same problem.

**Comment by KenHaffner** [comment]
Dear Josh,

 

Thank you for your reply.

I did wrote alone a similar SW in Python, I did manage to simulate multiple species spectra taking into account the different concentrations but unfortunately hapiest is not capable to do so!

Do you envisage in the near future to implement such approach?

Thank you for your support.

Best

Ken

**Comment by jkarns275** [comment]
Yes! That will be added when I start working on HAPIEST full time again (i.e. after the spring semester ends). I'll open an issue for that now so I don't forget.

**Comment by jkarns275** [comment]
If you could explain a little more specifically what functionality you would like to see regarding mixing ratios, I would really appreciate it! I'm not a spectroscopist myself so any insights you may have would be very useful

**Comment by KenHaffner** [comment]
I will try to explain what I did.

In the selection window of the molecules you have to give the list of all species available in HITRAN16, the user can than select more than one and you fetch all corresponding lines in the database. You may also ask for a linestrengh threshold in order to suppress the weak lines and speed up the calculation!
In the last window (graphic) you have to open a new window where the user should give the concentration of each specie in % (a unit converter should be available ppb, ppm) the sum should be always one if below you may ask the user if he want air or nitrogen for the rest.
Like in your window it will be best to have a popup for the conditions:
Pressure, lineshape, temperature, pathlength, pressure shift etc.
Your graph window is fine, a linemarker should be available in order to show the molecule corresponding to the position of the cursor, it is helpful to identify certain lines in the spectrum.
