### ISSUE TITLE
Hapiest does not recognize internet connection. 

### ISSUE THREAD

**Issue by zrohde2** [hitranonline/hapiest#45]
I am trying to run hapiest, I couldn't get it to run by doing the bash command, I had to try to run the hapiest.exe itself. I am doing all of this on a mac.

When I did this, it opened up a prompt to enter my api key, which I did. Then when it tries to run I get a box that says "You do not have a working internet connection. You need to have a working internet connection in order to use hapiest."

I do have an internet connection. Why would this error occur?

I have basically no python or coding knowledge in general, just an fyi. I was very excited to see that hapiest existed instead of trying to run hapi.py.

**Comment by jkarns275** [comment]
Ah, I've not done much testing on the Mac! Just to try and diagnose this: when you run the program, does a terminal window open up in addition to the user interface? If so, can you copy and paste what it says or take a screenshot?

**Comment by jkarns275** [comment]
Also: as for running it as a bash command, what did you try? I want to update the instructions in the README.md if they are not clear enough

**Comment by zrohde2** [comment]
When I try to run the hapiest.exe, this is what shows up. 

The top left box is my terminal that opens up the error on the top right. 

I believe I just ran “bash hapiest.sh”. This gave me an error saying that the bin directory did not exist when I got the files using the git command. When I downloaded it using the link, the bash command no longer returns anything.

**Comment by jkarns275** [comment]
If you attached in image to that email, it looks like github ignored it. Try uploading it to imgur.com or something similar and sending the link.

**Comment by zrohde2** [comment]
Maybe this will work.

https://imgur.com/a/0QO2hWe

**Comment by jkarns275** [comment]
That does work! But it looks like there is not a lot of clues in that screenshot. I don't have access to a Mac machine so testing for mac is hard. 

Here is what I can try to do: I'll add some additional diagnostic code to the program and add it to the github, then I'lll ask you to run it from bash. 

You need a version of python 3 installed, the newer the better.

You also need these libraries installed through pip:
`PyQt5`
`PyQtChart`
`vispy`
`numpy`
`matplotlib`
`toml`

Each one of these can be installed using the command line like this:

`python3 -m pip install <package name>`
where package name is one of the packages listed above. You might need to add `sudo` to the beginning of the command to install packages. 

Once you've done that, try pulling from github again or downloading the most version of the source, and running using `python3 src`.

This is a big ask so if you don't have the time thats ok, I'll see if my coworker can test it out for me

**Comment by zrohde2** [comment]
That worked!

Thank you for your help.

**Comment by jkarns275** [comment]
Very glad to hear it! The executables are a little outdated so perhaps the issue was already fixed! If you have any feedback, feature requests, or bug reports don't hesitate to open another issue :)

**Comment by jkarns275** [comment]
Closing this since it only applies to the old executable and not the current version of the source code.

**Comment by zrohde2** [comment]
I also had to download parsy to get it to work.

**Comment by jkarns275** [comment]
Whoops - I forgot about that one! I'll add it to a list on the README.md so people know which packages they should install beforehand
