### ISSUE TITLE
Hapiest crashes when editing cross-sections filter

### ISSUE THREAD

**Issue by zrohde2** [hitranonline/hapiest#46]
No cross section filters can be applied because the program crashes. Last lines in terminal read:

WARNING: Traceback (most recent call last):
  File "src/widgets/cross_section_fetch_widget.py", line 110, in __on_apply_filters_clicked
    self.set_cross_section_list_items(xsc_filter.get_cross_sections())
  File "src/data_structures/xsc.py", line 74, in get_cross_sections
    if self.molecule_id not in CrossSectionMeta.molecule_metas:
AttributeError: type object 'CrossSectionMeta' has no attribute 'molecule_metas'
Abort trap: 6

Am I just not doing something correctly?

**Comment by jkarns275** [comment]
Nope this is a bug! I'll push a fix in a little while.

**Comment by jkarns275** [comment]
Ok I just pushed a fix for this, it should work now. Can you confirm the fix worked?

**Comment by zrohde2** [comment]
Confirmed. Program no longer crashes.

**Comment by jkarns275** [comment]
Great! Will close this issue for now.
